In [1]:
import torch

# Calculate the dot product between two vectors
vector_a = torch.tensor([1, 2, 3])
vector_b = torch.tensor([4, 5, 6])

dot_product_result = torch.dot(vector_a, vector_b)
print(f"The dot product of {vector_a} and {vector_b} is: {dot_product_result.item()}")

# Calculate the matrix multiplication of two 2-dimensional matrices
matrix_a = torch.tensor([[1, 2], [3, 4]])
matrix_b = torch.tensor([[5, 6], [7, 8]])

matrix_mult_result = torch.mm(matrix_a, matrix_b)
print(f"The matrix multiplication of\n{matrix_a}\nand\n{matrix_b}\nis:\n{matrix_mult_result}")


The dot product of tensor([1, 2, 3]) and tensor([4, 5, 6]) is: 32
The matrix multiplication of
tensor([[1, 2],
        [3, 4]])
and
tensor([[5, 6],
        [7, 8]])
is:
tensor([[19, 22],
        [43, 50]])


In [2]:
import tensorflow as tf

# Define the vectors
vector_a = tf.constant([1, 2, 3], dtype=tf.float32)
vector_b = tf.constant([4, 5, 6], dtype=tf.float32)

# Calculate the dot product
dot_product_result = tf.tensordot(vector_a, vector_b, axes=1)
print(f"The dot product of {vector_a.numpy()} and {vector_b.numpy()} is: {dot_product_result.numpy()}")

# Define the matrices
matrix_a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
matrix_b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Calculate the matrix multiplication
matrix_mult_result = tf.matmul(matrix_a, matrix_b)
print(f"The matrix multiplication of\n{matrix_a.numpy()}\nand\n{matrix_b.numpy()}\nis:\n{matrix_mult_result.numpy()}")


The dot product of [1. 2. 3.] and [4. 5. 6.] is: 32.0
The matrix multiplication of
[[1. 2.]
 [3. 4.]]
and
[[5. 6.]
 [7. 8.]]
is:
[[19. 22.]
 [43. 50.]]
